---
title: "STA 104-final project-1,2"
author: "Jun Wei,Xiaoyi Xu"
date: "11/28/2021"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 3. Methods and Results
### (1).(a)
```{r}
library(readxl)
data = read_xlsx("hollywoodmovies.xlsx")
budget = data$Budget
dgp  = data$DomesticGross
ow = data$OpeningWeekend
par(mfrow=c(1,3))
hist(budget)
hist(dgp)
hist(ow)
```
```{r}
budget_ave = mean(budget)
budget_ave
dgp_ave = mean(dgp)
dgp_ave
ow_ave = mean(ow)
ow_ave
```


```{r}
budget_m = median(budget)
budget_m
dgp_m = median(dgp)
dgp_m
ow_m = median(ow)
ow_m
```

```{r}
library(distributions3)
n <- length(budget)
T_ <- StudentsT(df = n-1)
mean(budget) + quantile(T_, 0.05 / 2) * sd(budget) / sqrt(n)
mean(budget) + quantile(T_, 1 - 0.05 / 2) * sd(budget) / sqrt(n)

t.test(budget, conf.level = 0.95)
```

```{r}
n <- length(dgp)
T_ <- StudentsT(df = n-1)
mean(dgp) + quantile(T_, 0.05 / 2) * sd(dgp) / sqrt(n)
mean(dgp) + quantile(T_, 1 - 0.05 / 2) * sd(dgp) / sqrt(n)

t.test(dgp, conf.level = 0.95)
```

```{r}
n <- length(ow)
T_ <- StudentsT(df = n-1)
mean(ow) + quantile(T_, 0.05 / 2) * sd(ow) / sqrt(n)
mean(ow) + quantile(T_, 1 - 0.05 / 2) * sd(ow) / sqrt(n)

t.test(ow, conf.level = 0.95)
```

### (1).(b)

```{r}
num = 0
for (i in 1:n){
  if (budget[i]<=budget_ave){
    num = num+1
  }
}
num
pbinom(num,n,0.5,lower.tail = F)
```

```{r}
num = 0
for (i in 1:n){
  if (dgp[i]<=dgp_ave){
    num = num+1
  }
}
num
pbinom(num,n,0.5,lower.tail = F)
```

```{r}
num = 0
for (i in 1:n){
  if (ow[i]<=ow_ave){
    num = num+1
  }
}
num
pbinom(num,n,0.5,lower.tail = F)
```

```{r}
a = -qnorm(1-0.05/2)*sqrt(0.25*n)+0.5*n
a
b = qnorm(1-0.05/2)*sqrt(0.25*n)+0.5*n+1
b
a_star = floor(a)
a_star
b_star = ceiling(b)
b_star
```


```{r}
budget_order = sort(budget)
budget_order[a_star]
budget_order[b_star]
```


```{r}
dgp_order = sort(dgp)
dgp_order[a_star]
dgp_order[b_star]
```


```{r}
ow_order = sort(ow)
ow_order[a_star]
ow_order[b_star]
```


## (2)
```{r}
budget_c = data$Budget[data$Genre=="Comedy"]
budget_d = data$Budget[data$Genre=="Drama"]
p1 = hist(budget_c) 
p2 = hist(budget_d) 
plot(p1,col=rgb(0,0,1,1/4),main = "histogram of budget",xlab="budget_c and budget_d") 
plot(p2, col=rgb(1,0,1,1/4),add=T) 

```

```{r}
dgp_c = data$DomesticGross[data$Genre=="Comedy"]
dgp_d = data$DomesticGross[data$Genre=="Drama"]
p1 = hist(dgp_c) 
p2 = hist(dgp_d) 
plot(p1,col=rgb(0,0,1,1/4),main = "histogram of dgp",xlab="dgp_c and dgp_d") 
plot(p2, col=rgb(1,0,1,1/4),add=T) 

ow_c = data$OpeningWeekend[data$Genre=="Comedy"]
ow_d = data$OpeningWeekend[data$Genre=="Drama"]
p1 = hist(ow_c) 
p2 = hist(ow_d) 
plot(p1,col=rgb(0,0,1,1/4),main = "histogram of ow",xlab = "ow_c and ow_d") 
plot(p2, col=rgb(1,0,1,1/4),add=T) 
```



```{r}
t.test(budget_c,budget_d,alternative = "greater")
wilcox.test(budget_c,budget_d,alternative = "greater")
```


```{r}
t.test(dgp_c,dgp_d,alternative = "greater")
wilcox.test(dgp_c,dgp_d,alternative = "greater")
```


```{r}
t.test(ow_c,ow_d,alternative = "greater")
wilcox.test(ow_c,ow_d,alternative = "greater")
```


```{r}
var(budget_c)
var(budget_d)
```

```{r}
var(dgp_c)
var(dgp_d)
```


```{r}
var(ow_c)
var(ow_d)
```


